//
// Created by olcay on 14.03.2019.
//

#ifndef DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H
#define DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H

enum class TurkishDependencyType{
    VOCATIVE, SUBJECT, DATIVE_ADJUNCT, OBJECT, POSSESSOR,
    MODIFIER, S_MODIFIER, ABLATIVE_ADJUNCT, DETERMINER, SENTENCE,
    CLASSIFIER, LOCATIVE_ADJUNCT, COORDINATION, QUESTION_PARTICLE, INTENSIFIER,
    INSTRUMENTAL_ADJUNCT, RELATIVIZER, NEGATIVE_PARTICLE, ETOL, COLLOCATION,
    FOCUS_PARTICLE, EQU_ADJUNCT, APPOSITION
};
#endif //DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H
